-- 回滚初始迁移
DROP TABLE IF EXISTS operation_logs CASCADE;
DROP TABLE IF EXISTS goal_templates CASCADE;
DROP TABLE IF EXISTS meal_records CASCADE;
DROP TABLE IF EXISTS plan_items CASCADE;
DROP TABLE IF EXISTS meal_plans CASCADE;
DROP TABLE IF EXISTS foods CASCADE;
DROP TABLE IF EXISTS users CASCADE;
